name: "Build MKS-Klipad50 Image"
on:
  #push:
  #  tags:
  #    - '*'

  workflow_dispatch:
    inputs:

      #armbian_target:
      #  type: choice
      #  description: 'Build'
      #  required: false
      #  options:
      #  - kernel
      #  - build
      #  default: build

      #armbian_kernel_branch:
      #  type: choice
      #  description: 'Kernel branch'
      #  options:
      #  - legacy
      #  - current
      #  - edge
      #  default: 'current'

      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        - jammy
        - mantic
        - bookworm
        - trixie
        - sid
        default: 'bookworm'

      #armbian_ui:
      #  type: choice
      #  description: 'User interface (not all works)'
      #  options:
      #  - minimal
      #  - server
      #  default: 'server'

      #armbian_version:
      #  description: 'Version'
      #  required: false
      #  default: ''

      #armbian_board:
      #  type: choice
      #  description: 'Board'
      #  options:
      #  - mksklipad50
      #  - mkspi
      #  default: 'mksklipad50'

      #mksklipad50_branch:
      #  type: choice
      #  description: 'MKS-Klipad50:Branch'
      #  options:
      #  - decompiled
      #  - main
      #  default: 'main'

      mksklipad50_compress:
        type: choice
        description: 'MKS-Klipad50:Compress'
        options:
        - img
        - xz
        - sha,xz
        - sha,gpg,xz
        default: 'sha,xz'

      mksklipad50_minimal:
        type: boolean
        description: 'MKS-Klipad50:Minimal'
        default: 'false'

      mksklipad50_desktop:
        type: boolean
        description: 'MKS-Klipad50:Desktop'
        default: 'false'

      mksklipad50_bspfreeze:
        type: boolean
        description: 'MKS-Klipad50:BSPFreeze'
        default: 'false'

      tag_bump:
        type: choice
        description: 'Bump version'
        options:
        - patch
        - minor
        - major
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        #with:
          #repository: 'armbian/build'
          #ref: ${{inputs.mksklipad50_branch}}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          default_bump: ${{inputs.tag_bump}}

      - name: Build
        shell: bash
        run: |
          if [[ ${{inputs.mksklipad50_minimal}} == "true" ]] ; then BUILD_MINIMAL=yes ; else BUILD_MINIMAL=no ; fi
          if [[ ${{inputs.mksklipad50_desktop}} == "true" ]] ; then BUILD_DESKTOP=yes ; else BUILD_DESKTOP=no ; fi
          if [[ ${{inputs.mksklipad50_bspfreeze}} == "true" ]] ; then BSPFREEZE=yes ; else BSPFREEZE=no ; fi
          # test
          git clone https://github.com/armbian/build --no-tags --single-branch --no-recurse-submodules --depth=1
          cd build
          #mkdir -p output/images ; touch output/images/testfile
          for kernel in edge current ; do \
            ./compile.sh \
              BOARD=mksklipad50 \
              BRANCH=$kernel \
              RELEASE=${{inputs.armbian_release}} \
              BUILD_MINIMAL=$BUILD_MINIMAL \
              BUILD_DESKTOP=$BUILD_DESKTOP \
              BSPFREEZE=$BSPFREEZE \
              COMPRESS_OUTPUTIMAGE=${{inputs.mksklipad50_compress}} \
              KERNEL_CONFIGURE=no \
          ; done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Armbian-unofficial-MKS-Klipad50
          path: build/output/images/
          #path: output/images/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Armbian-unofficial-MKS-Klipad50/*"
          #tag: ${{ steps.checkout.outputs.ref }}
          commit: ${{ steps.checkout.outputs.commit }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
